#!/bin/sh
if [ "${LD_LIBRARY_PATH+set}" = "set" ] ; then
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/fso/freespace2"
else
export LD_LIBRARY_PATH="/opt/fso/freespace2"
fi
cd "/opt/fso/freespace2" &&
exec ./freespace2 "$@"
